### PR TITLE
Bump NLog from 5.0.0 to 5.0.2

### PR DESCRIPTION
**Pull request by snakefoot**
NLog 5.0.2 with better handling of typed Layout - https://github.com/NLog/NLog/pull/5019

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot imo this should be 5.0.1. Otherwise this package use a different versioning compared to other packages?

**Comment by snakefoot** [comment]
I like having matching versions (when possible). Ex. NLog.MailKit v5.0.2 matching NLog v5.0.2 (Or NLog.Extensions.Logging v5.0.4 matching NLog v5.0.4)

**Comment by 304NotModified** [comment]
I think skipping versions is confusing. 

Also imo when doing updates as a user, its the best for us all (maintainers and users) to also update the dependencies (patch level at least), it saves work for the user, it has the latest bugfixes and the user doesn't need to be aware of the dependencies under the hood (or at least, less)

**Comment by 304NotModified** [comment]
Also benefit for all, it this package is using the latest dependencies,  your are more sure it works with those versions as the unit tests also use that version.

**Comment by snakefoot** [comment]
I guess that I'm coming from a world where nothing is a "safe" update, and version-lock-in from dependencies can become poison when trying to patch a critical issue that is completely unrelated to the dependencies.

But I approve of updating to the nearest patch-version. Guess I just have to be more strict with bumping minor-version whenever a feature is introduced. Next version must be NLog v5.1

About strict patch-versions, then I have no religion there, as long it is increasing. It seems very few people care about "gaps" in the version-series. Even see some use the build-number as patch-version-number.

**Pull request merged**
