### PR TITLE
Added SkipCertificateValidation option

### PR DESCRIPTION
**Pull request by razonrus**
for sending by smtp server with invalid certificate

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

I think it's "ignore error" or "skip validation", what do you think?

**Comment by razonrus** [comment]
I get `System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.` in my case. I think it is important to specify Certificate error or Certificate validation in the flag name

**Comment by 304NotModified** [comment]
Yes I will merge this,

but I mean, the name "IgnoreCertificateValidation" isn't correct IMO.

It should be:

- a) IgnoreCertificateValidationErrors **or**
- b) SkipCertificateValidation

What has your preference? Please update the PR then, thanks!

**Comment by 304NotModified** [comment]
Would be also possible to add an unit test? Please check the current unit tests.

**Comment by razonrus** [comment]
OK, I rename flag to SkipCertificateValidation and add description to readme.

I could not simulate invalid certificate in unit test. Also current tests need to revised — they are blinking for my envorinment and not correct: sending wrong username/password to smtpServer don't bring test failing. I think it's separate issue.

**Comment by 304NotModified** [comment]
OK cool! Thanks!

**Comment by 304NotModified** [comment]
FYI, I have updated the docs here:

https://github.com/NLog/NLog/wiki/Mail-target

**Comment by 304NotModified** [comment]
1.1 is online! :)

**Comment by razonrus** [comment]
Great! Thank you!
Docs at https://github.com/NLog/NLog/wiki/Mail-Target are common for classic NLog MailTarget and NLog.MailKit, right? For classic NLog option "skipCertificateValidation" will not work

**Comment by 304NotModified** [comment]
Yes indeed. I added the note.

**Pull request merged**
