### PR TITLE
NLog 5 compatible, all properties layoutable, Update MailKit

### PR DESCRIPTION
**Pull request by 304NotModified**
- [x] NLog 5 compatible
- [x] All properties layoutable
- [x] Fix obsolete `NLogRuntimeException`
- [x] Update changelog
- [x] Update package and icon
- [x] Update MailKit
- [x] Readme in package
- [x] VS 2022 build
- [x] Tests in .NET 6 instead of EOL .NET 5
- [x] Cleanup
- [x] Double check

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe also add support for Layout everything, so SmtpPort + Timeout can be configured from external config-file:

```c#
public Layout<int> SmtpPort { get; set; } = 25;
public Layout<int> Timeout { get; set; } = 10000;
public Layout<MailPriority> Priority { get; set; }
```

https://github.com/NLog/NLog/blob/dev/src/NLog/Targets/MailTarget.cs

**Comment by 304NotModified** [comment]
Good idea! Thanks!

**Comment by 304NotModified** [comment]
Please check @snakefoot , thanks!

**Comment by snakefoot** [comment]
I guess the "correct" way is using `RenderLogEvent`-method on the Target-class. Instead of calling `RenderValue`

**Comment by 304NotModified** [comment]
Lol thats confusing

**Comment by snakefoot** [comment]
Target-RenderLogEvent is faster than Layout.Render and RenderValue-extension-method (Which are there for convience)

**Review by snakefoot — APPROVED** [review]

**Pull request merged**
